version: '3.7'

x-build: &build
  context: .
  dockerfile: ./docker/Dockerfile
  target: ci

services:
  ci_sh_default: &default
    build:
      <<: *build
      args:
        SH_VERSION: default
    volumes:
      - "$PWD:/usr/local/src/super_unko"
    working_dir: /usr/local/src/super_unko
    entrypoint:
      - ./test.sh

  ci_sh_3.2:
    <<: *default
    build:
      <<: *build
      args:
        # Because bats supports 3.2.57 or more https://github.com/bats-core/bats-core
        SH_VERSION: 3.2.57

  ci_sh_4.0:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 4.0

  ci_sh_4.1:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 4.1

  ci_sh_4.2:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 4.2

  ci_sh_4.3:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 4.3

  ci_sh_4.4:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 4.4

  ci_sh_5.0:
    <<: *default
    build:
      <<: *build
      args:
        SH_VERSION: 5.0
