version: '3'

services:
  formatter:
    image: peterdavehello/shfmt:2.6.4
    container_name: formatter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shfmt"
      - "-i"
      - "2"
      - "-ci"
      - "-sr"
      - "-d"

  linter:
    image: koalaman/shellcheck:stable
    container_name: linter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shellcheck"
