name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Set tag to .tar2package.yml
        run: sed -i 's:\$VERSION:${{ steps.vars.outputs.tag }}:g' .tar2package.yml
      - run: Print .tar2package.yml
      - name: Generate packages
        run: ./package.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            - pkg/*.deb
            - pkg/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

